<?php
/*
	review panes commerce_checkout_review_pane_checkout_form()

@todo
	-	validation (?) is mirroring billing into shipping (can't change shipping)
	-	should this be a multistep form ? ( see examples module )
	-	should this be multiple forms on one page ?
	- add test credentials
*/

define("CEC_TEST_MODE", TRUE);

function commerce_expresscheckout_preprocess_html(&$variables) {
//      drupal_add_js(drupal_get_path('module', 'views') . '/js/views-contextual.js', array('group' => JS_LIBRARY, 'weight' => -1));
	drupal_add_js(drupal_get_path('module', 'commerce_expresscheckout'), "/js/commerce_expresscheckout.js");
}


/* 
	Instance of hook_menu
	Creates our path for the one page checkout
	@todo can we override the default?
*/
function commerce_expresscheckout_menu() {
	drupal_add_js(drupal_get_path('module', 'commerce_expresscheckout'), "/js/commerce_expresscheckout.js");
	$items = array(); 
//	$items['checkout/%/express'] = array( 
//	$items['checkout/%'] = array( 
	$items['expresscheckout/%'] = array( 
      'title' => 'Express checkout', 
      'weight' => 20,
      'description' => t('Checkout quickly on one page.'), 
      'page callback' => 'drupal_get_form', 
//		inherited from checkout if path is checkout/%/express
//      'access' => user_access('access checkout'),
      'access arguments' => array('access checkout'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'page arguments' => array('commerce_expresscheckout_form', 1),
	);
  
	return $items;

}


/*
	Implements hook_form
	Creates a form for our checkout
*/
function commerce_expresscheckout_form($form, &$form_state, $order_id) {
//	if we commerce_order load then we redirect away.
	$order = commerce_order_load($order_id);
//	krumo($order);
//	$order = $order_id;
//	$order = null;
	$pages = commerce_checkout_pages();
	$panes = commerce_checkout_panes(array('enabled' => TRUE));

	$debug = CEC_TEST_MODE;
	$i = 1;
//	iterate over each of the pages (pane sets) looking for panes that belong in it
	foreach ($pages as $page_id => $checkout_page) {
//	create fieldsets
		$form[$page_id . '_fieldset'] = array(
			'#title' => t("Step " . $i++ . " – " . $checkout_page['title']),
			// The prefix/suffix provide the div that we're replacing, named by
			// #ajax['wrapper'] above.
			'#prefix' => '<div id="' . $page_id . '_div">',
			'#suffix' => '</div>',
			'#type' => 'fieldset',
			'#count' => 0,	//	used to store the number of panes herein
			'#description' => t($checkout_page['help']),
		);
		
		if ( $debug ) {
			$form[$page_id . '_fieldset']['#title'] .= " [" . $page_id . "]";
		}

		$k = 1;
		foreach ($panes as $pane_id => $checkout_pane_local) {
//	the redirect panes cause redirection (strangely) - we can't have that
			if ( strpos($pane_id, 'redirect') )
				continue;
			if ( $checkout_pane_local['page'] == $page_id ) {
				$form[$page_id . '_fieldset']['#count']++;
				
				$callback = commerce_checkout_pane_callback($checkout_pane_local, 'checkout_form');
        $pane_data = $callback($form, $form_state, $checkout_pane_local, $order);
//	from commerce_checkout.checkout_pane.inc
//	Only display the pane if there is data in the pane.
				if (!empty($pane_data)) {
				// Add a row for it in the review data.
					$number = ($i-1) + $k/10;
					$k++;
					$form[$page_id . '_fieldset'][$pane_id . '_fieldset'] = array(
						'#title' => t("@number " . $checkout_pane_local['title'], array('@number'=>$number)),
						'data' => $pane_data,
						'#prefix' => '<div id="' . $pane_id . '_div">',
						'#suffix' => '</div>',
						'#type' => 'fieldset',
						'#collapsed' => FALSE,
						'#collapsible' => TRUE,
						//'#description' => t($checkout_pane_local['help']),
					);
					if ( $debug ) {
						$form[$page_id . '_fieldset'][$pane_id . '_fieldset']['#title'] .= " [" . $pane_id . "]";
					}
				}
			}
		}
//	clean up fieldsets that aren't required
		if ( $form[$page_id . '_fieldset']['#count'] ) {
			$form[$page_id . '_fieldset']['#classes'][] = "panes-" . $form[$page_id . '_fieldset']['#count'];
		} else {
			unset($form[$page_id . '_fieldset']);
			$i--;
		}
		
	}
		
	_commerce_expresscheckout_form_extend(&$form);

//	@todo abstract out so we can move the pane from page to page	
	$form['checkout_fieldset']['customer_profile_billing_fieldset']['data']['commerce_customer_address']['und'][0]['country']['#ajax']['callback'] = '_commerce_expresscheckout_addressfield_callback';
	$form['checkout_fieldset']['customer_profile_shipping_fieldset']['data']['commerce_customer_address']['und'][0]['country']['#ajax']['callback'] = '_commerce_expresscheckout_addressfield_callback';

//	krumo($form);
/*
	print "<pre>";
	print_r($form);
	print "</pre>";
*/
	return $form;
}


function _commerce_expresscheckout_test($form, $form_state) { 
  return "TEST"; 
}
	
	
/* 	
	repair callbacks from addressfields
	from addressfield.module fn addressfield_standard_widget_refresh 
*/
function _commerce_expresscheckout_addressfield_callback($form, $form_state) {
//	the default
//	return addressfield_standard_widget_refresh($form, $form_state);

  // The target element is one element below the triggering country selector.	
  $array_parents = $form_state['triggering_element']['#array_parents'];
  array_pop($array_parents);

  // Iterate over the form parents to find the element.
//	our form is nested one layer deep
//  $element = $form;
  $element = $form[$array_parents[0]];
  foreach ($array_parents as $name) {
    $element = &$element[$name];
    if (!empty($element['#addressfield'])) {
      break;
    }
  }

  // Return the address block, but remove the '_weight' element inserted
  // by the field API.
  unset($element['_weight']);
  return $element;
}

/*
	Implements hook_form_validate
*/
function commerce_expresscheckout_form_validate() {
	
}


/*
	Implements hook_form_submit
*/
function commerce_expresscheckout_form_submit() {
	
}

/*
	Settings
	- Override default checkout or not
*/


/*
 *	Modify incoming form with ajaxy goodness and additional fields as required
 */
function _commerce_expresscheckout_form_extend(&$form) {
//	add in next buttons per section
	$i = 1;
	foreach ( commerce_checkout_pages() as $page_id=>$page_data ) {
		$container_id = $page_id . "_fieldset";
		$field = array($page_id . '_next' => array(
//	if values aren't different then the ajax callback calls the wrong method
	    	'#value' => t('Step ' . ++$i . ' >'),
	    	'#type' => 'button',		
		));
		if ( $page_id == 'complete' ) {
			$field[$page_id . '_next']['#value'] = t("Finished");
		}
		_commerce_expresscheckout_form_add_field(&$form, $container_id, $field);		
		_commerce_expresscheckout_form_add_ajax_callback(&$form, $page_id, $page_id . '_next');
	};
	
//	_commerce_expresscheckout_form_add_ajax_callback(&$form, 'checkout_next', 'checkout');
	
//	modify the ajax response for addressfield as the form too nested for its call back to find
//	function addressfield_standard_widget_refresh($form, $form_state) {
//	form-item-commerce-customer-address-und-0-country
//	edit-commerce-customer-address-und-0-country
	//	customer_profile_billing
//	_commerce_expresscheckout_form_add_ajax_callback(&$form, 'shipping_country', 'customer_profile_shipping');
	
/*
	$form['submit'] = array(
    	'#type' => 'submit',
    	'#value' => t('Submit'),
		'#form_id' => "commerce_expresscheckout_form",
	);
*/

//  if we're testing add test data.
  if ( CEC_TEST_MODE ) {
    $form['checkout_fieldset']['account_fieldset']['data']['login']['mail']['#default_value'] = 'user@example.com';
//    $form['checkout_fieldset']['customer_profile_billing_fieldset']['commerce_customer_address']['und'][0]['name_line']['#default_value'] = 'user@example.com';
  }

}

function _commerce_expresscheckout_default_callback($form, $form_state) {
  	$array_parents = $form_state['triggering_element']['#array_parents'];
//	remove the trigger
	array_pop($array_parents);
//	this is our parent
	$parent = array_pop($array_parents);
//	 return (var_export($form[$parent], TRUE));
	return $form[$parent];	
}


function _commerce_expresscheckout_checkout_callback($form, $form_state) {
	error_log('called _commerce_expresscheckout_checkout_callback');
	return _commerce_expresscheckout_default_callback($form, $form_state);
}


function _commerce_expresscheckout_review_callback($form, $form_state) {
	return _commerce_expresscheckout_default_callback($form, $form_state);
}


function _commerce_expresscheckout_complete_callback($form, $form_state) {
	error_log('called _commerce_expresscheckout_complete_callback');
	return _commerce_expresscheckout_default_callback($form, $form_state);
}


/* iterate over the form for the correct trigger and add our callback */
function _commerce_expresscheckout_form_add_ajax_callback(&$form, $container_id, $trigger_id) {
	foreach ( $form as $id=>&$fields ) {
		if ( $id == $trigger_id ) {
			$fields['#ajax'] = array(
		      'callback' => '_commerce_expresscheckout_' . $container_id .'_callback',
		      'wrapper' => $container_id . '_div',
		      'method' => 'replace',
		      'effect' => 'fade',
		    );
			error_log($trigger_id . ' -> ' . $fields['#ajax']['callback']);
			return;
		}
		if ( is_array($fields) && array_key_exists('#type', $fields) ) {
			if ( $fields['#type'] == 'fieldset' ) {
				_commerce_expresscheckout_form_add_ajax_callback(&$form[$id], $container_id, $trigger_id);
			}
		}
	}
}

/* add a new field to the correct parent element */
function _commerce_expresscheckout_form_add_field(&$form, $container_id, $field) {
	foreach ( $form as $id=>&$fields ) {
		if ( $id == $container_id ) {
			$fields = array_merge_recursive($fields, $field);
//			$fields["#collapsed"] = FALSE;
			return;
		}
		if ( is_array($fields) && array_key_exists('#type', $fields) ) {
			if ( $fields['#type'] == 'fieldset' ) {
				_commerce_expresscheckout_form_add_field(&$form[$id], $container_id, $field);
			}
		}
	}
}
